package com.example.exceptions;

import java.sql.SQLException;

public class ExceptionsDemo {
	
	// no matter whether this throws exception or not, while calling you must use try-catch
	public static void store() throws SQLException {
		System.out.println("store() method is called");
	}
	// compiler ignores unchecked exception and doesn't expect to call this within try-catch 
	public static void div() throws ArithmeticException {
		System.out.println("div() method is called");
	}
	// create a main method & call store() and div() in main() 
	public static void main(String[] args) {
		System.out.println("***** main starts *****");
		try {
			store();
		} catch(SQLException e) {
			System.err.println(e);
			System.err.println(e.getMessage()); // prints the main error message
		}
		System.out.println("***** main ends *****");
	}
}
