package com.example.exceptions;

import java.sql.SQLException;

public class ExceptionsDemo {
	
	// no matter whether this throws exception or not, while calling you must use try-catch
	public static void store() throws SQLException {
		System.out.println("store() method is called");
	}
	public static void div() throws ArithmeticException {
		System.out.println("div() method is called");
	}
}
